export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CLIENTS_ROUTE = '/'
export const DOCTORS_ROUTE = '/doctors'
export const RECEPTIONS_ROUTE = '/receptions'
export const RECEPTION_ROUTE = '/reception'
export const CLIENT_ROUTE = '/client'